version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    image: rushilgoel/dockerapp
    environment:
      - constraint:node==master
    depends_on:
      - redis
    networks:
      - mynet

  redis:
    extends:
      file: common.yml
      service: redis
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
